### ISSUE TITLE
Error at edu.wpi.first.wpilibj.MotorSafety.check(MotorSafety.java:140): DifferentialDrive... Output not updated often enough. See https://docs.wpilib.org/motorsafety for more information.

### ISSUE THREAD

**Issue by julianalg** [MarauderTech-FRC-9573/2024-crescendo#12]

**Comment by rake6682** [comment]
https://www.chiefdelphi.com/t/error-1-differentialdrive-output-not-updated-often-enough/400909 might be helpful?

**Comment by julianalg** [comment]
resolved with running `differentialDrive.feed();`with each run of arcadeDrive. will push to main once im done with other controller adjustments
