### ISSUE TITLE
Simulation code not working with CAN motor change

### ISSUE THREAD

**Issue by julianalg** [MarauderTech-FRC-9573/2024-crescendo#19]
[CAN SPARK] IDs: 4, Parameter type mismatch for parameter id Getting Product ID parameter failed. Unable to account for device-specific behavior differences.

[CAN SPARK] IDs: 4, Error Invalid Cannot set motor type to kBrushed for SPARK without a dock connected.
libc++abi: terminating
zsh: abort      /usr/bin/env    /Users/julianalg/wpilib/2024/jdk/bin/java   frc.robot.Main

**Comment by rake6682** [comment]
Simulation appears to work for me

**Comment by julianalg** [comment]
could have been a mac thing then

**Comment by rake6682** [comment]
Closed PR already
